site_name: 信工所青年团员大学习专栏
pages:
    - 专栏介绍: '/intro'
    - 信息聚合:
        - '习近平同团中央新一届领导班子成员集体谈话（新闻稿）': '/news/news1'
        - '在中国共产主义青年团第十八次全国代表大会上的致词': '/news/news2'
        - '在新时代党的阳光照耀下前进——习近平总书记关心关怀青年和青年工作纪实': '/news/news3'
        - '殷殷嘱托 切切期望——学习领悟以习近平同志为核心的党中央对共青团工作的关心指导': '/news/news4'
        - '在中国共产主义青年团第十八次全国代表大会上的报告': '/news/news5'
        - '共青团中央关于全团深入学习领会习近平总书记“7·2”重要讲话精神切实抓好团的十八大精神学习宣传贯彻工作的通知': '/news/news6'
        - '中国共产主义青年团章程': '/news/news7'
theme:
    name: mkdocs
    custom_dir: theme_journal/
