site_name: 信工所青年团员大学习专栏
pages:
    - 专栏介绍: 'index.md'
    - 信息聚合:
        - '习近平同团中央新一届领导班子成员集体谈话（新闻稿）': 'news/news1.md'
        - '在中国共产主义青年团第十八次全国代表大会上的致词': 'news/news2.md'
        - '在新时代党的阳光照耀下前进——习近平总书记关心关怀青年和青年工作纪实': 'news/news3.md'
        - '殷殷嘱托 切切期望——学习领悟以习近平同志为核心的党中央对共青团工作的关心指导': 'news/news4.md'
        - '在中国共产主义青年团第十八次全国代表大会上的报告': 'news/news5.md'
        - '共青团中央关于全团深入学习领会习近平总书记“7·2”重要讲话精神切实抓好团的十八大精神学习宣传贯彻工作的通知': 'news/news6.md'
        - '中国共产主义青年团章程': 'news/news7.md'
    - 工作综述:
        - '乘新时代东风 放飞青春梦想——写在共青团十八大开幕之际': 'summarize/summarize1.md'
        - '指引新时代共青团事业发展的青春盛会——写在“新时代的共青团”专栏开栏之际': 'summarize/summarize2.md'
        - '在改革中奋进的共青团——近年来共青团深化改革工作综述': 'summarize/summarize3.md'
        - '构筑青年一代的强大精神支柱——五年来共青团开展青年思想引导工作综述': 'summarize/summarize4.md'
        - '奏响青春建功新时代的奋进强音——五年来共青团服务大局工作综述': 'summarize/summarize5.md'
        - '坚持服务青年的工作生命线——五年来共青团服务青年发展工作综述': 'summarize/summarize6.md'
        - '让青少年想得起、找得到、靠得住——五年来共青团维护青少年权益工作综述': 'summarize/summarize7.md'
        - '打造“网上共青团”——五年来共青团网络新媒体工作综述': 'summarize/summarize8.md'
        - '共青团的伙伴们——五年来共青团新兴领域青年工作综述': 'summarize/summarize9.md'
        - '严出战斗力 严出新形象——五年来共青团加强团员和团干部队伍建设综述': 'summarize/summarize10.md'
        - '打通联系凝聚团员青年的“最后一公里”——五年来共青团基层组织建设综述': 'summarize/summarize11.md'
    - 系列评论:
        - '在习近平总书记关于青年工作的重要思想指引下奋勇前行——一论学习贯彻习近平总书记同团中央新一届领导班子成员集体谈话时的重要讲话精神': 'comment/comment1.md'
        - '当好党的助手和后备军——二论学习贯彻习近平总书记同团中央新一届领导班子成员集体谈话时的重要讲话精神': 'comment/comment2.md'
        - '以壮士断腕、刮骨疗伤的决心推进共青团改革和全面从严治团——三论学习贯彻习近平总书记同团中央新一届领导班子成员集体谈话时的重要讲话精神': 'comment/comment3.md'
        - '新时代青年和共青团工作的光辉指南——一论学习贯彻习近平总书记关于青年工作的重要思想': 'comment/comment4.md'
        - '马克思主义青年观的丰富和发展——二论学习贯彻习近平总书记关于青年工作的重要思想': 'comment/comment5.md'
        - '牢牢把握中国青年运动的时代主题——三论学习贯彻习近平总书记关于青年工作的重要思想': 'comment/comment6.md'
        - '坚持党管青年——四论学习贯彻习近平总书记关于青年工作的重要思想': 'comment/comment7.md'


theme:
    name: mkdocs
    custom_dir: theme_journal/
